default_index:
    path: /
    defaults: { _controller: "AppBundle:Default:index" }
    methods: GET
#Carga el controlador que esta en AppBundle la clase Default y el metodo index

default_pruebas:
    path: /pruebas
    defaults: { _controller: "AppBundle:Default:pruebas" }
    methods: GET